language: ruby
rvm:
  - 2.3.0
before_install: gem install bundler -v 1.11.2
bundler_args: --without visual
script:
  - bundle exec rake
addons:
  code_climate:
    repo_token: 92a88ea7fed1022e2d0e9a3879f4937be99e94ca
